import ClassificationFiniteSimpleGroupsCanonicalLaneLean.Basic
import ClassificationFiniteSimpleGroupsCanonicalLaneLean.GateLemmas
import ClassificationFiniteSimpleGroupsCanonicalLaneLean.FinalTheorem
